---
- name: Setup AdGuard Home
  hosts: adguard # Note that you can also specify the host here
  tasks:
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - curl
          - docker.io
          - docker-compose
        state: present
    
    - name: Deploy AdGuard Home container
      ansible.builtin.docker_container:
        name: adguard
        image: adguard/adguardhome
        state: started

# BUG: example code

---
- name: Deploy AdGuard Home service
  hosts: adguard
  become: yes # become sudo

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: /opt/adguard
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml file
      ansible.builtin.copy:
        src: files/docker-compose-adguard.yml
        dest: /opt/adguard/docker-compose.yml
        mode: '0644'

    - name: Deploy the AdGuard Home service with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/adguard
        state: present
        
    - name: Verify service is running
      ansible.builtin.command: docker-compose -f /opt/adguard/docker-compose.yml ps
      register: compose_ps_output
      changed_when: false
      
    - name: Display service status
      ansible.builtin.debug:
        var: compose_ps_output.stdout_lines
