services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared
    hostname: cloudflared
    restart: unless-stopped
    network_mode: 'host'
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/cloudflare/config/:/etc/cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN} # place this variable inside a .env
      - TUNNEL_POST_QUANTUM=${CLOUDFLARE_TUNNEL_POST_QUANTUM} # place this variable inside a .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
