services:

  # =================================================================
  #                   VPN + qBittorrent
  # =================================================================

  # gluetun =========================================================
  gluetun:
    container_name: gluetun
    hostname: gluetun.internal
    image: ghcr.io/qdm12/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696 # Prowlarr Web UI
      - 8080:8080 # qBittorrent Web UI
      # Don't need to map these anymore
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      # - 6881:6881 # qBittorrent Torrent Port
      # - 6881:6881/udp
    environment:
      - PUID=0
      - PGID=0
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=CJMzLQon5i8SiCsDOzn9SiJ/t7bpC6xSrPHZC0pToF8=
      - WIREGUARD_PRESHARED_KEY=SeDVVrgLdlMOSe0VUhqhCYRsNCpXy1yPaWEOuy5yLb4=
      - WIREGUARD_ADDRESSES=10.187.94.226/32
      - FIREWALL_VPN_INPUT_PORTS=33433
      - SERVER_COUNTRIES=Netherlands
      # Timezone
      - TZ=Europe/Lisbon
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/gluetun:/config

  # qbittorrent =====================================================
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    # ports:
    #   - 8080:8080 # qBittorrent Web UI
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /data/:/data

  # autobrr =========================================================
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - ./autobrr/config:/config
    ports:
      - 7474:7474

  # =================================================================
  #                           seerr
  # =================================================================
  seerr:
    container_name: seerr
    hostname: seerr.internal
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Lisbon
      - PORT=5055 #optional
    volumes:
      - ./seerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped


  # =================================================================
  #                       *arr stack
  # =================================================================

  # prowlarr ========================================================
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config

  # flaresolverr (helper for prowlarr) ==============================
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Lisbon

  # radarr ==========================================================
  radarr:
    container_name: radarr
    hostname: radarr.internal
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data

  # sonarr ==========================================================
  sonarr:
    container_name: sonarr
    hostname: sonarr.internal
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data

  # lidarr ==========================================================
  lidarr:
    container_name: lidarr
    hostname: lidarr.internal
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8686:8686
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /data:/data


  # readarr =========================================================
  # WARNING: need to find a replacement
  # readarr:
  #   container_name: readarr
  #   hostname: readarr.internal
  #   image: ghcr.io/hotio/readarr:latest
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #   ports:
  #     - 8787:8787
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=Europe/Lisbon
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /docker/appdata/readarr:/config
  #     - /data:/data

  # bazarr ==========================================================
  bazarr:
    container_name: bazarr
    hostname: bazarr.internal
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
