services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    environment:
      - TS_AUTHKEY=<your_auth_key>
      - TS_ROUTES=192.168.1.0/24
      - TS_HOSTNAME=homelab
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

volumes:
  tailscale_data:
