services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - CF_API_TOKEN=your_massive_cloudflare_api_token_here
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
