server:
  assets-path: /app/assets
branding:
  hide-footer: true
  # logo-url: https://your_logo_url
  # favicon-url: https://your_icon_url
theme:
  custom-css-file: /assets/style.css

pages:
  - $include: home.yml
  - $include: tech.yml
  - $include: news.yml
  - $include: other.yml
