---
- hosts: nextcloud-lxc
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Create Nextcloud directories
      file:
        path: "/mnt/storage/nextcloud"
        state: directory
        owner: 1000
        group: 1000

    - name: Deploy Nextcloud stack
      copy:
        src: ../templates/nextcloud-compose.yml
        dest: /opt/nextcloud/docker-compose.yml
      notify: Restart Nextcloud

  handlers:
    - name: Restart Nextcloud
      command: docker-compose -f /opt/nextcloud/docker-compose.yml up -d
